export const SCHEMES = [
  {
    id: "micro",
    code: "NSFDC-MCF",
    name: "Micro Finance Scheme",
    category: "Micro Credit / Small Business",
    badge: "Most Popular for Vendors & Artisans",
    rate: 6.5,
    maxCost: 140000,
    minCost: 5000,
    moratorium: 3,
    maxTenureMonths: 36,
    incomeLimit: 500000,
    coveragePercent: 90,
    description: "Concessional credit for small retail shops, street vending, artisanal crafts, and micro enterprises. Up to 90% of project cost funded at 6.5% interest rate.",
    suitableFor: ["Grocery / Kirana Shop", "Street Vending / Pushcart", "Tailoring / Embroidery", "Handicrafts & Carpentry", "Dairy / Poultry Unit"],
    color: "#2E7D32"
  },
  {
    id: "term",
    code: "NSFDC-TL",
    name: "Term Loan Scheme",
    category: "Medium Enterprise & Fabrication",
    badge: "For Growth & Capital Equipment",
    rate: 8.0,
    maxCost: 5000000,
    minCost: 140001,
    moratorium: 6,
    maxTenureMonths: 84,
    incomeLimit: 500000,
    coveragePercent: 90,
    description: "Subsidized term loans for setting up production units, service businesses, light engineering, processing centers, or purchasing commercial vehicles.",
    suitableFor: ["Small Manufacturing", "Automobile Workshop", "IT / Hardware Center", "Food Processing", "Commercial Transport"],
    color: "#1565C0"
  },
  {
    id: "education",
    code: "NSFDC-ELS",
    name: "Education Loan Scheme",
    category: "Higher & Professional Education",
    badge: "Lowest 4% Concessional Rate",
    rate: 4.0,
    maxCost: 2000000,
    minCost: 20000,
    moratorium: 12,
    maxTenureMonths: 120,
    incomeLimit: 500000,
    coveragePercent: 90,
    description: "Highly subsidized educational credit for professional, technical, engineering, and medical degrees in India (up to ₹20 Lakh) and Abroad (up to ₹40 Lakh).",
    suitableFor: ["B.Tech / Engineering", "MBBS / Healthcare", "MBA / Management", "Polytechnic / Diploma", "Recognized Degree Courses"],
    color: "#7B1FA2"
  },
  {
    id: "aajeevika",
    code: "NSFDC-AMFY",
    name: "Aajeevika Micro-Finance Yojana",
    category: "Fast NBFC-MFI Channel",
    badge: "Fast Doorstep Disbursal",
    rate: 15.0,
    maxCost: 140000,
    minCost: 5000,
    moratorium: 3,
    maxTenureMonths: 36,
    incomeLimit: 500000,
    coveragePercent: 90,
    description: "Rapid micro-credit channeled through empaneled NBFC-MFIs for quick business restart and self-help group members without complex collateral.",
    suitableFor: ["SHG Members", "Door-to-door sales", "Agri-allied livelihood", "Immediate working capital"],
    color: "#C27803"
  }
];
